### PR TITLE
config: addition of more meaningful facets

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
screen shot 2017-03-16 at 15 56 45

**Comment by jmartinm** [comment]
@drjova Shall we add all of them or we add just the first one and we leave adding the rest for our tutorial?

Did you try if the sorting was working?

**Comment by drjova** [comment]
@jmartinm On our tutorial we can add `Authors` and explain them also a bit of the issue and how they can fix it, WDYT?

**Comment by jmartinm** [comment]
> On our tutorial we can add Authors and explain them also a bit of the issue and how they can fix it, WDYT?

We can, although it goes into the topic of ES, mappings and so on. I guess for our basic tutorial trying to fix it (which would involve change mappings, reindex) would be too much, so we can just explain it as you say.

**Review by lnielsen — APPROVED** [review]

**Comment by drjova** [comment]
@jmartinm I don't think we need to go too deep on that, just to explain what is going on

**Pull request merged**
